### ISSUE TITLE
Windows installation problem...

### ISSUE THREAD

**Issue by ahmetanildindar** [bollwyvl/nb-mermaid#2]
Dear all,
I'd like to use your program in my NB's but installation yields with an error as seen below. 
![image](https://cloud.githubusercontent.com/assets/3111609/17865369/f79ad0d8-68aa-11e6-9653-48280e6e9b15.png)

My config is  Windows 7 Professional and Jupyter ver 4.1.0
Any suggestion?

Thank you.

**Comment by riedelcastro** [comment]
I have a similar issue (on Macs), see below. I suppose this suggests ipython versions over 4.0 are not supported. Will there be support for this? 

```
~/p/nam ❯❯❯ pip3 install nb-mermaid                                           ⏎
Collecting nb-mermaid
  Downloading nb-mermaid-0.1.0.tar.gz (161kB)
    100% |████████████████████████████████| 163kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Collecting jupyter-pip
      Downloading jupyter-pip-0.3.tar.gz
    Building wheels for collected packages: jupyter-pip
      Running setup.py bdist_wheel for jupyter-pip: started
      Running setup.py bdist_wheel for jupyter-pip: finished with status 'done'
      Stored in directory: /Users/riedel/Library/Caches/pip/wheels/fc/d1/54/fe00cc99454ad2e7500e2c0ef1f811aaa356e1cb92c5bcb4c2
    Successfully built jupyter-pip
    Installing collected packages: jupyter-pip
    Successfully installed jupyter-pip-0.3
    /usr/local/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
      "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/my/nvfq6hqn6l58mzb1vyt0zs240000gn/T/pip-build-rl8baxut/nb-mermaid/setup.py", line 41, in <module>
        setup(**setup_data)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1115, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (ipython 4.2.0 (/usr/local/lib/python3.5/site-packages), Requirement.parse('IPython<4.0,>3.0'))

```
