### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by nocibambi** [bollwyvl/nb-mermaid#8]
Hi, I tried to install the extension with pip, but received the following error message:

```bash
>> pip install nb-mermaid
Collecting nb-mermaid
  Downloading https://files.pythonhosted.org/packages/b9/40/c721865ce3ce642a335b22cdc565586017636337eeab4a40e59ad27e2fd1/nb-mermaid-0.1.0.tar.gz (161kB)
    100% |████████████████████████████████| 163kB 2.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-_yex9ock/nb-mermaid/setup.py", line 10, in <module>
        from jupyterpip import cmdclass
    ModuleNotFoundError: No module named 'jupyterpip'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_yex9ock/nb-mermaid/setup.py", line 15, in <module>
        pip.main(["install", "jupyter-pip"])
    AttributeError: module 'pip' has no attribute 'main'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_yex9ock/nb-mermaid/
```

**Comment by masbicudo** [comment]
I executed `pip install jupyter-pip` before and it got past that error... unfortunately another error raises:

```
Collecting nb-mermaid
  Using cached https://files.pythonhosted.org/packages/b9/40/c721865ce3ce642a335b22cdc565586017636337eeab4a40e59ad27e2fd1/nb-mermaid-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/IPython/: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto -- Some packages may not be found!
    No local packages or working download links found for IPython<4.0,>3.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-cremi2ds\nb-mermaid\setup.py", line 41, in <module>
        setup(**setup_data)
      File "c:\python\python36-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python\python36-32\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python\python36-32\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\python\python36-32\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python\python36-32\lib\site-packages\setuptools\command\easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('IPython<4.0,>3.0')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-cremi2ds\nb-mermaid\
```
